name: dart_cli
description: A simple Dart command line tool interacting with the OpenAI API.
version: 0.1.0
environment:
  sdk: '>=2.17.0 <4.0.0'
dependencies:
  args: ^2.4.0
  http: ^0.13.0

dev_dependencies:
  test: ^1.24.0
