name: CI

on:
  push:
  pull_request:

jobs:
  go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go-cli
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go-cli/go.mod
      - run: go test ./...

  rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust-cli
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo test --verbose

  dart:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dart-cli
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart test

  flutter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter-gui
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter test

  java:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: NetBeans
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - run: mvn -B test

  clojure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: clojure-cli
    steps:
      - uses: actions/checkout@v4
      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest
      - run: clojure -X:test

  perl:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: perl-cli
    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.38'
      - run: prove -I . t
